[tool.poetry]
name = "derakht"
version = "0.1.0"
description = ""
authors = ["arianhf <arian.hedayatifar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
wagtail = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
