# Generated by Django 4.2.5 on 2023-10-06 13:55

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_books',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='books.book'),
        ),
    ]
